/*
-- Criação da tabela USUARIO
CREATE TABLE USUARIO (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);*/
/*
-- Criação da tabela CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    IDUSUARIO INT NOT NULL,
    nome_cliente VARCHAR(100) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

-- Criação da tabela FORNECEDOR
CREATE TABLE FORNECEDOR (
    IDFORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    IDUSUARIO INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

-- Criação da tabela CATEGORIA
CREATE TABLE CATEGORIA (
    IDCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL, -- Nome da categoria
    descricao TEXT              -- Descrição opcional da categoria
);

-- Criação da tabela PRODUTO
CREATE TABLE PRODUTO (
    IDPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    IDCATEGORIA INT NOT NULL,
    designacao VARCHAR(100) NOT NULL, -- Nome ou descrição do produto
    data DATE NOT NULL,
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

-- Criação da tabela FORNECEDOR_PRODUTO
CREATE TABLE FORNECEDOR_PRODUTO (
    IDFORNECEDOR INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    PRIMARY KEY (IDFORNECEDOR, IDPRODUTO),
    FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

-- Criação da tabela VENDA
CREATE TABLE VENDA (
    IDVENDA INT AUTO_INCREMENT PRIMARY KEY,
    IDCLIENTE INT NOT NULL,
    data DATE NOT NULL,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
*/

